import * as React from "react";
import Layout from "../components/Layout";
import { getPagePath, useLocalization, withPageLanguage } from "../utils/localization";
import { cn } from "../utils/cn";
import Seo from "../components/Seo";
// import * as CSS from "./_tos-and-privacy.module.scss";

const TermsOfService = () => {
    const [t] = useLocalization();

    return (
        <Layout>
            <Seo
                title={t("pages.privacy.meta.title")}
                description={t("pages.termsOfService.meta.description")}
                url={getPagePath()}
            />
            <main className={cn("tosAndPrivacyPage", "terms-of-service wrapper")}>
                <h2>{t("pages.termServices.termheading")}</h2>
                <p>{t("pages.termServices.publishdate")}</p>

                <p>
                {t("pages.termServices.termDescription")}
                </p>

                <ol>
                    <li>
                        <h3>{t("pages.termServices.DefinitionsHeading")}</h3>
                        <p>{t("pages.termServices.DefinitionsHeading-p1")}</p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p2")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p3")}
                        </p>
                        <p>{t("pages.termServices.DefinitionsHeading-p4")}</p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p5")}
                        </p>
                        <p>{t("pages.termServices.DefinitionsHeading-p6")}</p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p7")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p8")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p9")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p10")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p11")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p12")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p13")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p14")}
                        </p>
                        <p>
                        {t("pages.termServices.DefinitionsHeading-p15")}
                        </p>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.DescriptionerviceHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p3")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p4")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p5")}
                                </p>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p6")}
                                </p>
                                <p>
                                {t("pages.termServices.DescriptionerviceHeading-p7")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.RightofrevocationHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.RightofrevocationHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.RightofrevocationHeading-p2")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.UserAccountsHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.UserAccountsHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.UserAccountsHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.UserAccountsHeading-p3")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.UserAccountsHeading-p4")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.PaymentsHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.PaymentsHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.PaymentsHeading-p2")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.IntellectualHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.IntellectualHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.IntellectualHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.IntellectualHeading-p3")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.AdditionalHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p3")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p4")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p5")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p6")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p7")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p8")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AdditionalHeading-p9")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.terminationHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.terminationHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.terminationHeading-p2")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.DefectsHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.DefectsHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DefectsHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.DefectsHeading-p3")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.ApplicableHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.ApplicableHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.ApplicableHeading-p2")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.ApplicableHeading-p3")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.AmendmentsHeading")}</h3>
                        <ol>
                            <li>
                                <p>{t("pages.termServices.AmendmentsHeading-p1")}</p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AmendmentsHeading-p2")}
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <h3>{t("pages.termServices.AssignmentHeading")}</h3>
                        <ol>
                            <li>
                                <p>
                                {t("pages.termServices.AssignmentHeading-p1")}
                                </p>
                            </li>
                            <li>
                                <p>
                                {t("pages.termServices.AssignmentHeading-p2")}
                                </p>
                            </li>
                        </ol>
                    </li>
                </ol>
                <p>{t("pages.termServices.update")}</p>
            </main>
        </Layout>
    );
};

export default withPageLanguage(TermsOfService);
